[project]
name = "iris"
version = "0.1"
description = "Seed cracking & prediction via measurement of random blinks in Pokemon BDSP"

[tool.cxfreeze]
executables = [{ script = "main.py", base = "gui" }]

[tool.cxfreeze.build_exe]
includes = ["PySide6.QtMultimediaWidgets"]
